### ISSUE TITLE
Issue with connecting to remote agent on coreos

### ISSUE THREAD

**Issue by snowping** [CenturyLinkLabs/panamax-remote-agent#19]
Hi,

I installed the panamax agent to a coreos running the stable and beta release. When I add the deployment target and try to refresh the target through the Panamax ui it shows: undefined method `message=' for #
![image](https://cloud.githubusercontent.com/assets/1017254/5165925/2a6080f0-73eb-11e4-9c4e-7a904dd07dd1.png)
![image](https://cloud.githubusercontent.com/assets/1017254/5165938/461311b4-73eb-11e4-8699-c66685131ae6.png)

In the agent log I got the following (docker logs pmx_agent): 
Puma starting in single mode...
* Version 2.8.2 (ruby 2.1.2-p95), codename: Sir Edmund Percival Hillary
* Min threads: 0, max threads: 16
* Environment: production
* Listening on ssl://0.0.0.0:3000?key=/usr/local/share/certs/pmx_remote_agent.key&cert=/usr/local/share/certs/pmx_remote_agent.crt
Use Ctrl-C to stop
I, [2014-11-24T00:49:55.057351 #15]  INFO -- : Started GET "/metadata" for 192.168.17.253 at 2014-11-24 00:49:55 +0000
I, [2014-11-24T00:49:55.060350 #15]  INFO -- : Processing by MetadataController#show as */*
E, [2014-11-24T00:49:55.066555 #15] ERROR -- :
NoMethodError (undefined method `info' for nil:NilClass):

Deployment using fleet api seems working though.

CoreOS running:
NAME=CoreOS
ID=coreos
VERSION=494.0.0
VERSION_ID=494.0.0

**Comment by patocox** [comment]
Closing
